// Generated by CoffeeScript 1.4.0
(function() {

  jQuery(function() {
    var _this = this;
    this.popbox = "<div id=\"more-mails\" class=\"more-items\">\n  <div class=\"bd\">\n    <p id=\"mail-loading\" style=\"display: none;\">邮件读取中...</p>\n    <ul>\n    </ul>\n  </div>\n  <div class=\"ft\">\n    <a href=\"http://www.douban.com/doumail/\">查看全部邮件</a>\n  </div>\n</div>";
    this.mailLink = $('.top-nav-info a').first();
    this.mailLink.parent().css('position', 'relative');
    this.mailLink.click(function() {
      $('#mail-loading').show();
      $('#more-mails').find('ul').empty();
      $('#more-mails').toggle();
      $.get('http://www.douban.com/doumail/', function(res) {
        var mails, match, regex, table;
        mails = [];
        regex = /<table class="olt".+>[^]+<\/table>/gm;
        match = regex.exec(res);
        table = $(match[0]);
        table.find('tr').each(function(index, tr) {
          var from, time, topic;
          if ((0 < index && index < 6)) {
            from = $(tr).find('td').eq(0).html();
            if ($(from).find('a')) {
              from = $(from).html();
            } else {
              from = $(from).text();
            }
            topic = $(tr).find('td').eq(2).html();
            time = $(tr).find('td').eq(3).html();
            return mails.push({
              from: from,
              topic: topic,
              time: time
            });
          }
        });
        $('#mail-loading').hide();
        $.each(mails, function(index, mail) {
          return $('#more-mails').find('ul').append("<li><div id='mail_notify_" + index + "' class='item-req'>来之" + mail.from + "的" + mail.topic + " - " + mail.time + "</div></li>");
        });
        return $('#more-mails').find('ul a').attr('target', '_blank');
      });
      return false;
    });
    return this.mailLink.after(this.popbox);
  });

}).call(this);
